import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:uuid/uuid.dart';
import '../../../core/constants/app_constants.dart';
import '../../../core/services/providers.dart';
import '../../../data/datasources/rag_service.dart';
import '../../../data/models/test_model.dart';
import 'test_preview_screen.dart';

class TestBuilderScreen extends ConsumerStatefulWidget {
  const TestBuilderScreen({super.key});

  @override
  ConsumerState<TestBuilderScreen> createState() => _TestBuilderScreenState();
}

class _TestBuilderScreenState extends ConsumerState<TestBuilderScreen> {
  TestType _testType = TestType.autoGenerated;
  final List<String> _selectedSources = [];
  final List<String> _selectedTopics = [];

  DifficultyMode _difficultyMode = DifficultyMode.mixed;
  final int _easyPercent = AppConstants.defaultMixedEasyPercent;
  final int _mediumPercent = AppConstants.defaultMixedMediumPercent;
  final int _hardPercent = AppConstants.defaultMixedHardPercent;

  int _questionCount = 10;
  int _easyTime = AppConstants.defaultEasyTimeSeconds;
  int _mediumTime = AppConstants.defaultMediumTimeSeconds;
  int _hardTime = AppConstants.defaultHardTimeSeconds;

  double _correctMarks = AppConstants.defaultCorrectMarks;
  double _negativeMarks = AppConstants.defaultNegativeMarks;
  bool _negativeMarkingEnabled = AppConstants.defaultNegativeMarkingEnabled;
  bool _strictModeNoPrevious = false;

  bool _isGenerating = false;

  @override
  void initState() {
    super.initState();
    _initAutoSelections();
  }

  void _initAutoSelections() {
    // Select all available sources by default
    final sourcesRepo = ref.read(sourcesRepositoryProvider);
    _selectedSources.clear();
    for (final s in sourcesRepo.sources) {
      _selectedSources.add(s.sourceId);
    }

    // Auto select topics from weak topics & available syllabus
    _selectedTopics.clear();
    _selectedTopics.addAll([
      'Network Analysis',
      'Boolean Algebra & Combinational Circuits',
    ]);
  }

  void _generateAndValidateTest() {
    final sources = ref.read(sourcesRepositoryProvider).sources;
    final questions = ref.read(questionsRepositoryProvider).questions;

    if (sources.isEmpty && questions.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('No study materials or questions found. Please import materials into the Question Bank first.'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() => _isGenerating = true);

    final testId = const Uuid().v4();

    // Execute Strict RAG Generation and Validation
    final result = RAGService.generateExamQuestions(
      allSources: sources,
      availableQuestionBank: questions,
      selectedSourceIds: _selectedSources,
      selectedSubjects: const [],
      selectedTopics: _selectedTopics,
      selectedSubtopics: const [],
      difficultyMode: _difficultyMode,
      easyPercentage: _easyPercent,
      mediumPercentage: _mediumPercent,
      hardPercentage: _hardPercent,
      requestedCount: _questionCount,
      easyTime: _easyTime,
      mediumTime: _mediumTime,
      hardTime: _hardTime,
      testId: testId,
    );

    setState(() => _isGenerating = false);

    if (result.generatedCount == 0) {
      showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
          title: const Text('Insufficient Study Material'),
          content: Text(result.statusMessage),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.pop(ctx);
                context.go('/question-bank');
              },
              child: const Text('Open Question Bank & Import'),
            ),
            ElevatedButton(
              onPressed: () => Navigator.pop(ctx),
              child: const Text('Change Topics'),
            ),
          ],
        ),
      );
      return;
    }

    final testModel = TestModel(
      testId: testId,
      userId: ref.read(authRepositoryProvider).currentUser?.id ?? '',
      title: _testType == TestType.autoGenerated
          ? 'ISRO Auto-Generated Mock Test'
          : 'ISRO Custom Practice Test',
      testType: _testType,
      selectedSources: _selectedSources,
      selectedTopics: _selectedTopics,
      difficultyMode: _difficultyMode,
      easyPercentage: _easyPercent,
      mediumPercentage: _mediumPercent,
      hardPercentage: _hardPercent,
      questionCount: result.generatedCount,
      easyTime: _easyTime,
      mediumTime: _mediumTime,
      hardTime: _hardTime,
      correctMarks: _correctMarks,
      negativeMarks: _negativeMarks,
      negativeMarkingEnabled: _negativeMarkingEnabled,
      strictModeNoPrevious: _strictModeNoPrevious,
      questions: result.questions,
      createdAt: DateTime.now(),
    );

    // If actual questions were fewer than requested, show mandatory verification prompt
    if (result.hasInsufficientSources) {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (ctx) => AlertDialog(
          title: Row(
            children: [
              const Icon(Icons.warning_amber_rounded, color: Colors.amber),
              const SizedBox(width: 8),
              const Text('Source Material Validation'),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                '⚠ ONLY ${result.generatedCount} QUESTIONS COULD BE GENERATED FROM SELECTED STUDY MATERIALS.',
                style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.red),
              ),
              const SizedBox(height: 8),
              Text('Requested: $_questionCount'),
              Text('Valid Grounded Questions: ${result.generatedCount}'),
              const SizedBox(height: 12),
              const Text(
                'The AI engine strictly adheres to your study materials and will never fabricate questions outside user sources.',
                style: TextStyle(fontSize: 12, fontStyle: FontStyle.italic),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(ctx),
              child: const Text('Cancel / Change Topics'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(ctx);
                _openTestPreview(testModel, result);
              },
              child: Text('Start with ${result.generatedCount} Questions'),
            ),
          ],
        ),
      );
    } else {
      _openTestPreview(testModel, result);
    }
  }

  void _openTestPreview(TestModel test, RAGGenerationResult result) {
    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (ctx) => TestPreviewScreen(test: test, ragResult: result),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final sourcesRepo = ref.watch(sourcesRepositoryProvider);
    final allTopics = [
      'Network Analysis',
      'Boolean Algebra & Combinational Circuits',
      'Continuous & Discrete Signals',
      'Semiconductor Physics',
      'Operational Amplifiers & Oscillators',
    ];

    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 820),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Header
              const Text(
                'AI TEST GENERATOR',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, letterSpacing: 1.0),
              ),
              const SizedBox(height: 4),
              const Text(
                'Generate exam-style tests strictly grounded in your study materials. Per-question timers, negative marking, and source attribution are applied.',
                style: TextStyle(fontSize: 13, color: Colors.grey),
              ),
              const SizedBox(height: 20),

              // Test Mode Selector
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Row(
                    children: [
                      const Text(
                        'TEST MODE:',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
                      ),
                      const SizedBox(width: 16),
                      ChoiceChip(
                        label: const Text('Auto-Generated Test'),
                        selected: _testType == TestType.autoGenerated,
                        onSelected: (_) => setState(() => _testType = TestType.autoGenerated),
                      ),
                      const SizedBox(width: 8),
                      ChoiceChip(
                        label: const Text('Custom Test'),
                        selected: _testType == TestType.custom,
                        onSelected: (_) => setState(() => _testType = TestType.custom),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Source Selection
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'STUDY SOURCES (STRICT GROUNDING)',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF1E3A8A),
                            ),
                          ),
                          TextButton(
                            onPressed: () {
                              setState(() {
                                if (_selectedSources.length == sourcesRepo.sources.length) {
                                  _selectedSources.clear();
                                } else {
                                  _selectedSources.clear();
                                  _selectedSources.addAll(sourcesRepo.sources.map((s) => s.sourceId));
                                }
                              });
                            },
                            child: Text(_selectedSources.length == sourcesRepo.sources.length ? 'Deselect All' : 'Select All'),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      if (sourcesRepo.sources.isEmpty)
                        const Text('No uploaded materials found. Please upload materials in Upload Hub.')
                      else
                        Wrap(
                          spacing: 8,
                          runSpacing: 8,
                          children: sourcesRepo.sources.map((s) {
                            final isSel = _selectedSources.contains(s.sourceId);
                            return FilterChip(
                              label: Text(s.sourceName, style: const TextStyle(fontSize: 12)),
                              selected: isSel,
                              onSelected: (val) {
                                setState(() {
                                  if (val) {
                                    _selectedSources.add(s.sourceId);
                                  } else {
                                    _selectedSources.remove(s.sourceId);
                                  }
                                });
                              },
                            );
                          }).toList(),
                        ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Topic Selection
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'TOPIC SELECTION',
                        style: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF1E3A8A),
                        ),
                      ),
                      const SizedBox(height: 8),
                      Wrap(
                        spacing: 8,
                        runSpacing: 8,
                        children: allTopics.map((topic) {
                          final isSel = _selectedTopics.contains(topic);
                          return FilterChip(
                            label: Text(topic, style: const TextStyle(fontSize: 12)),
                            selected: isSel,
                            onSelected: (val) {
                              setState(() {
                                if (val) {
                                  _selectedTopics.add(topic);
                                } else {
                                  _selectedTopics.remove(topic);
                                }
                              });
                            },
                          );
                        }).toList(),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Question Count & Difficulty
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text('Number of Questions:', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                                const SizedBox(height: 8),
                                Wrap(
                                  spacing: 6,
                                  children: [5, 10, 15, 20, 30].map((c) {
                                    return ChoiceChip(
                                      label: Text('$c'),
                                      selected: _questionCount == c,
                                      onSelected: (_) => setState(() => _questionCount = c),
                                    );
                                  }).toList(),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text('Difficulty Mode:', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                                const SizedBox(height: 8),
                                DropdownButtonFormField<DifficultyMode>(
                                  initialValue: _difficultyMode,
                                  decoration: const InputDecoration(contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 8)),
                                  items: DifficultyMode.values.map((d) {
                                    return DropdownMenuItem(value: d, child: Text(d.label));
                                  }).toList(),
                                  onChanged: (v) {
                                    if (v != null) setState(() => _difficultyMode = v);
                                  },
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Timers and Marking System
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'PER-QUESTION TIMER & MARKING SCHEME',
                        style: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF1E3A8A),
                        ),
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: TextFormField(
                              initialValue: '$_easyTime',
                              keyboardType: TextInputType.number,
                              decoration: const InputDecoration(labelText: 'Easy Time (sec)'),
                              onChanged: (v) => _easyTime = int.tryParse(v) ?? 60,
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: TextFormField(
                              initialValue: '$_mediumTime',
                              keyboardType: TextInputType.number,
                              decoration: const InputDecoration(labelText: 'Medium Time (sec)'),
                              onChanged: (v) => _mediumTime = int.tryParse(v) ?? 90,
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: TextFormField(
                              initialValue: '$_hardTime',
                              keyboardType: TextInputType.number,
                              decoration: const InputDecoration(labelText: 'Hard Time (sec)'),
                              onChanged: (v) => _hardTime = int.tryParse(v) ?? 120,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 16),
                      Row(
                        children: [
                          Expanded(
                            child: TextFormField(
                              initialValue: '+$_correctMarks',
                              decoration: const InputDecoration(labelText: 'Correct Marks'),
                              onChanged: (v) => _correctMarks = double.tryParse(v.replaceAll('+', '')) ?? 1.0,
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: TextFormField(
                              initialValue: '$_negativeMarks',
                              decoration: const InputDecoration(labelText: 'Negative Marks'),
                              onChanged: (v) => _negativeMarks = double.tryParse(v) ?? -0.25,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      SwitchListTile(
                        contentPadding: EdgeInsets.zero,
                        title: const Text('Negative Marking Enabled', style: TextStyle(fontSize: 14)),
                        subtitle: Text(
                          _negativeMarkingEnabled
                              ? 'Deducts ${_negativeMarks.abs()} marks for wrong answers'
                              : 'Disabled (0 marks deducted for wrong answers)',
                          style: const TextStyle(fontSize: 12),
                        ),
                        value: _negativeMarkingEnabled,
                        onChanged: (v) => setState(() => _negativeMarkingEnabled = v),
                      ),
                      SwitchListTile(
                        contentPadding: EdgeInsets.zero,
                        title: const Text('Strict Mode: No Previous Question', style: TextStyle(fontSize: 14)),
                        subtitle: const Text('Prevents navigating back to completed questions', style: TextStyle(fontSize: 12)),
                        value: _strictModeNoPrevious,
                        onChanged: (v) => setState(() => _strictModeNoPrevious = v),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),

              ElevatedButton.icon(
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  backgroundColor: const Color(0xFF1E3A8A),
                ),
                icon: _isGenerating
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
                      )
                    : const Icon(Icons.auto_awesome_rounded),
                label: Text(
                  _isGenerating ? 'Validating Sources & Generating...' : 'Generate & Preview Test',
                  style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                ),
                onPressed: _isGenerating ? null : _generateAndValidateTest,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

