import 'question_model.dart';

enum TestType {
  custom,
  autoGenerated;

  String get label => this == TestType.custom ? 'Custom Test' : 'Auto Generated';
}

enum DifficultyMode {
  easy,
  medium,
  hard,
  mixed;

  String get label {
    switch (this) {
      case DifficultyMode.easy:
        return 'Easy';
      case DifficultyMode.medium:
        return 'Medium';
      case DifficultyMode.hard:
        return 'Hard';
      case DifficultyMode.mixed:
        return 'Mixed';
    }
  }
}

enum TestQuestionStatus {
  unanswered,
  answered,
  markedForReview,
  timeUp;

  String get label {
    switch (this) {
      case TestQuestionStatus.unanswered:
        return 'Unanswered';
      case TestQuestionStatus.answered:
        return 'Answered';
      case TestQuestionStatus.markedForReview:
        return 'Marked for Review';
      case TestQuestionStatus.timeUp:
        return 'Time Up';
    }
  }
}

class TestQuestionModel {
  final String questionId;
  final String testId;
  final String sourceId;
  final String sourceName;
  final String sourceLocation;
  final String sourceChunk;
  final String questionText;
  final List<String> options;
  final String correctAnswer;
  final String solution;
  final Difficulty difficulty;
  final String subject;
  final String topic;
  final String? subtopic;
  final int timeAllowedSeconds;
  final int timeUsedSeconds;
  final String? userAnswer;
  final TestQuestionStatus status;
  final double marksAwarded;
  final bool? isCorrect;

  const TestQuestionModel({
    required this.questionId,
    required this.testId,
    required this.sourceId,
    required this.sourceName,
    this.sourceLocation = '',
    this.sourceChunk = '',
    required this.questionText,
    required this.options,
    required this.correctAnswer,
    this.solution = '',
    required this.difficulty,
    this.subject = '',
    this.topic = '',
    this.subtopic,
    required this.timeAllowedSeconds,
    this.timeUsedSeconds = 0,
    this.userAnswer,
    this.status = TestQuestionStatus.unanswered,
    this.marksAwarded = 0.0,
    this.isCorrect,
  });

  Map<String, dynamic> toJson() => {
    'questionId': questionId,
    'testId': testId,
    'sourceId': sourceId,
    'sourceName': sourceName,
    'sourceLocation': sourceLocation,
    'sourceChunk': sourceChunk,
    'questionText': questionText,
    'options': options,
    'correctAnswer': correctAnswer,
    'solution': solution,
    'difficulty': difficulty.name,
    'subject': subject,
    'topic': topic,
    'subtopic': subtopic,
    'timeAllowedSeconds': timeAllowedSeconds,
    'timeUsedSeconds': timeUsedSeconds,
    'userAnswer': userAnswer,
    'status': status.name,
    'marksAwarded': marksAwarded,
    'isCorrect': isCorrect,
  };

  factory TestQuestionModel.fromJson(Map<String, dynamic> json) =>
      TestQuestionModel(
        questionId: json['questionId'] as String,
        testId: json['testId'] as String? ?? '',
        sourceId: json['sourceId'] as String? ?? '',
        sourceName: json['sourceName'] as String? ?? 'Unknown',
        sourceLocation: json['sourceLocation'] as String? ?? '',
        sourceChunk: json['sourceChunk'] as String? ?? '',
        questionText: json['questionText'] as String,
        options: (json['options'] as List<dynamic>?)
                ?.map((e) => e.toString())
                .toList() ??
            const [],
        correctAnswer: json['correctAnswer'] as String,
        solution: json['solution'] as String? ?? '',
        difficulty: Difficulty.fromString(json['difficulty'] as String? ?? 'medium'),
        subject: json['subject'] as String? ?? '',
        topic: json['topic'] as String? ?? '',
        subtopic: json['subtopic'] as String?,
        timeAllowedSeconds: json['timeAllowedSeconds'] as int? ?? 90,
        timeUsedSeconds: json['timeUsedSeconds'] as int? ?? 0,
        userAnswer: json['userAnswer'] as String?,
        status: TestQuestionStatus.values.firstWhere(
          (e) => e.name == json['status'],
          orElse: () => TestQuestionStatus.unanswered,
        ),
        marksAwarded: (json['marksAwarded'] as num?)?.toDouble() ?? 0.0,
        isCorrect: json['isCorrect'] as bool?,
      );

  TestQuestionModel copyWith({
    String? questionId,
    String? testId,
    String? sourceId,
    String? sourceName,
    String? sourceLocation,
    String? sourceChunk,
    String? questionText,
    List<String>? options,
    String? correctAnswer,
    String? solution,
    Difficulty? difficulty,
    String? subject,
    String? topic,
    String? subtopic,
    int? timeAllowedSeconds,
    int? timeUsedSeconds,
    String? userAnswer,
    TestQuestionStatus? status,
    double? marksAwarded,
    bool? isCorrect,
  }) {
    return TestQuestionModel(
      questionId: questionId ?? this.questionId,
      testId: testId ?? this.testId,
      sourceId: sourceId ?? this.sourceId,
      sourceName: sourceName ?? this.sourceName,
      sourceLocation: sourceLocation ?? this.sourceLocation,
      sourceChunk: sourceChunk ?? this.sourceChunk,
      questionText: questionText ?? this.questionText,
      options: options ?? this.options,
      correctAnswer: correctAnswer ?? this.correctAnswer,
      solution: solution ?? this.solution,
      difficulty: difficulty ?? this.difficulty,
      subject: subject ?? this.subject,
      topic: topic ?? this.topic,
      subtopic: subtopic ?? this.subtopic,
      timeAllowedSeconds: timeAllowedSeconds ?? this.timeAllowedSeconds,
      timeUsedSeconds: timeUsedSeconds ?? this.timeUsedSeconds,
      userAnswer: userAnswer ?? this.userAnswer,
      status: status ?? this.status,
      marksAwarded: marksAwarded ?? this.marksAwarded,
      isCorrect: isCorrect ?? this.isCorrect,
    );
  }
}

class TestModel {
  final String testId;
  final String userId;
  final String title;
  final TestType testType;
  final List<String> selectedSources;
  final List<String> selectedSubjects;
  final List<String> selectedTopics;
  final List<String> selectedSubtopics;

  final DifficultyMode difficultyMode;
  final int easyPercentage;
  final int mediumPercentage;
  final int hardPercentage;

  final int questionCount;
  final int easyTime;
  final int mediumTime;
  final int hardTime;

  final double correctMarks;
  final double negativeMarks;
  final double unattemptedMarks;
  final bool negativeMarkingEnabled;

  final bool overallTimerEnabled;
  final int overallTimeSeconds;
  final bool strictModeNoPrevious;

  final List<TestQuestionModel> questions;
  final DateTime createdAt;
  final DateTime? startedAt;
  final DateTime? completedAt;
  final bool isCompleted;

  const TestModel({
    required this.testId,
    required this.userId,
    this.title = 'ISRO Practice Test',
    this.testType = TestType.custom,
    this.selectedSources = const [],
    this.selectedSubjects = const [],
    this.selectedTopics = const [],
    this.selectedSubtopics = const [],
    this.difficultyMode = DifficultyMode.mixed,
    this.easyPercentage = 30,
    this.mediumPercentage = 50,
    this.hardPercentage = 20,
    this.questionCount = 20,
    this.easyTime = 60,
    this.mediumTime = 90,
    this.hardTime = 120,
    this.correctMarks = 1.0,
    this.negativeMarks = -0.25,
    this.unattemptedMarks = 0.0,
    this.negativeMarkingEnabled = true,
    this.overallTimerEnabled = false,
    this.overallTimeSeconds = 0,
    this.strictModeNoPrevious = false,
    this.questions = const [],
    required this.createdAt,
    this.startedAt,
    this.completedAt,
    this.isCompleted = false,
  });

  Map<String, dynamic> toJson() => {
    'testId': testId,
    'userId': userId,
    'title': title,
    'testType': testType.name,
    'selectedSources': selectedSources,
    'selectedSubjects': selectedSubjects,
    'selectedTopics': selectedTopics,
    'selectedSubtopics': selectedSubtopics,
    'difficultyMode': difficultyMode.name,
    'easyPercentage': easyPercentage,
    'mediumPercentage': mediumPercentage,
    'hardPercentage': hardPercentage,
    'questionCount': questionCount,
    'easyTime': easyTime,
    'mediumTime': mediumTime,
    'hardTime': hardTime,
    'correctMarks': correctMarks,
    'negativeMarks': negativeMarks,
    'unattemptedMarks': unattemptedMarks,
    'negativeMarkingEnabled': negativeMarkingEnabled,
    'overallTimerEnabled': overallTimerEnabled,
    'overallTimeSeconds': overallTimeSeconds,
    'strictModeNoPrevious': strictModeNoPrevious,
    'questions': questions.map((q) => q.toJson()).toList(),
    'createdAt': createdAt.toIso8601String(),
    'startedAt': startedAt?.toIso8601String(),
    'completedAt': completedAt?.toIso8601String(),
    'isCompleted': isCompleted,
  };

  factory TestModel.fromJson(Map<String, dynamic> json) => TestModel(
    testId: json['testId'] as String,
    userId: json['userId'] as String? ?? '',
    title: json['title'] as String? ?? 'ISRO Practice Test',
    testType: TestType.values.firstWhere(
      (e) => e.name == json['testType'],
      orElse: () => TestType.custom,
    ),
    selectedSources: (json['selectedSources'] as List<dynamic>?)
            ?.map((e) => e.toString())
            .toList() ??
        const [],
    selectedSubjects: (json['selectedSubjects'] as List<dynamic>?)
            ?.map((e) => e.toString())
            .toList() ??
        const [],
    selectedTopics: (json['selectedTopics'] as List<dynamic>?)
            ?.map((e) => e.toString())
            .toList() ??
        const [],
    selectedSubtopics: (json['selectedSubtopics'] as List<dynamic>?)
            ?.map((e) => e.toString())
            .toList() ??
        const [],
    difficultyMode: DifficultyMode.values.firstWhere(
      (e) => e.name == json['difficultyMode'],
      orElse: () => DifficultyMode.mixed,
    ),
    easyPercentage: json['easyPercentage'] as int? ?? 30,
    mediumPercentage: json['mediumPercentage'] as int? ?? 50,
    hardPercentage: json['hardPercentage'] as int? ?? 20,
    questionCount: json['questionCount'] as int? ?? 20,
    easyTime: json['easyTime'] as int? ?? 60,
    mediumTime: json['mediumTime'] as int? ?? 90,
    hardTime: json['hardTime'] as int? ?? 120,
    correctMarks: (json['correctMarks'] as num?)?.toDouble() ?? 1.0,
    negativeMarks: (json['negativeMarks'] as num?)?.toDouble() ?? -0.25,
    unattemptedMarks: (json['unattemptedMarks'] as num?)?.toDouble() ?? 0.0,
    negativeMarkingEnabled: json['negativeMarkingEnabled'] as bool? ?? true,
    overallTimerEnabled: json['overallTimerEnabled'] as bool? ?? false,
    overallTimeSeconds: json['overallTimeSeconds'] as int? ?? 0,
    strictModeNoPrevious: json['strictModeNoPrevious'] as bool? ?? false,
    questions: (json['questions'] as List<dynamic>?)
            ?.map((e) => TestQuestionModel.fromJson(e as Map<String, dynamic>))
            .toList() ??
        const [],
    createdAt: json['createdAt'] != null
        ? DateTime.parse(json['createdAt'] as String)
        : DateTime.now(),
    startedAt: json['startedAt'] != null
        ? DateTime.parse(json['startedAt'] as String)
        : null,
    completedAt: json['completedAt'] != null
        ? DateTime.parse(json['completedAt'] as String)
        : null,
    isCompleted: json['isCompleted'] as bool? ?? false,
  );

  TestModel copyWith({
    String? testId,
    String? userId,
    String? title,
    TestType? testType,
    List<String>? selectedSources,
    List<String>? selectedSubjects,
    List<String>? selectedTopics,
    List<String>? selectedSubtopics,
    DifficultyMode? difficultyMode,
    int? easyPercentage,
    int? mediumPercentage,
    int? hardPercentage,
    int? questionCount,
    int? easyTime,
    int? mediumTime,
    int? hardTime,
    double? correctMarks,
    double? negativeMarks,
    double? unattemptedMarks,
    bool? negativeMarkingEnabled,
    bool? overallTimerEnabled,
    int? overallTimeSeconds,
    bool? strictModeNoPrevious,
    List<TestQuestionModel>? questions,
    DateTime? createdAt,
    DateTime? startedAt,
    DateTime? completedAt,
    bool? isCompleted,
  }) {
    return TestModel(
      testId: testId ?? this.testId,
      userId: userId ?? this.userId,
      title: title ?? this.title,
      testType: testType ?? this.testType,
      selectedSources: selectedSources ?? this.selectedSources,
      selectedSubjects: selectedSubjects ?? this.selectedSubjects,
      selectedTopics: selectedTopics ?? this.selectedTopics,
      selectedSubtopics: selectedSubtopics ?? this.selectedSubtopics,
      difficultyMode: difficultyMode ?? this.difficultyMode,
      easyPercentage: easyPercentage ?? this.easyPercentage,
      mediumPercentage: mediumPercentage ?? this.mediumPercentage,
      hardPercentage: hardPercentage ?? this.hardPercentage,
      questionCount: questionCount ?? this.questionCount,
      easyTime: easyTime ?? this.easyTime,
      mediumTime: mediumTime ?? this.mediumTime,
      hardTime: hardTime ?? this.hardTime,
      correctMarks: correctMarks ?? this.correctMarks,
      negativeMarks: negativeMarks ?? this.negativeMarks,
      unattemptedMarks: unattemptedMarks ?? this.unattemptedMarks,
      negativeMarkingEnabled:
          negativeMarkingEnabled ?? this.negativeMarkingEnabled,
      overallTimerEnabled: overallTimerEnabled ?? this.overallTimerEnabled,
      overallTimeSeconds: overallTimeSeconds ?? this.overallTimeSeconds,
      strictModeNoPrevious: strictModeNoPrevious ?? this.strictModeNoPrevious,
      questions: questions ?? this.questions,
      createdAt: createdAt ?? this.createdAt,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }
}

